### ISSUE TITLE
Premature exit of reader when consuming an iterable stream with empty blocks

### ISSUE THREAD

**Issue by jimpick** [ipld/js-car#46]
I encountered this issue when trying out web3.storage - I hit it when trying to store some data that had some zero length files in it.

https://github.com/web3-storage/web3.storage/issues/302

The data:

https://bafybeiatccvommze36x5cy44m22qz4al63riz4p6bnxw4pns6g3lbw3aky.ipfs.dweb.link/

I ended up writing a test program so I could test all the permutations. Here it is (along with results):

https://github.com/jimpick/js-car-zero-length-blocks

It appears that when consuming a streaming iterable, it sometimes will abort reading prematurely if the latest block has a zero length payload.

**Comment by rvagg** [comment]
ooof, thanks @jimpick, I fear we may be deep in the weeds on the writer in->out async channel complexity. Thanks for the test case, I'll get that integrated here as a proper test to help figure it out.

**Comment by rvagg** [comment]
comments over at https://github.com/jimpick/js-car-zero-length-blocks/pull/1

but if your client code needs more than `await`s to get the job done properly then let me know, I've had a poke around in the code and can't see anything obvious. There's a `write(Uint8Array([]))` going on which may impact a stream reader depending on its rules but that's not a problem with the example you've given (write to file), could be for some other stream decoder so that might be worth optimising out.
