### ISSUE TITLE
CarReader.fromIterable for large files

### ISSUE THREAD

**Issue by paulwongx** [ipld/js-car#87]
The documentation shows how to create a `carReader` when files are small as per below:

```js
import { CarReader } from '@ipld/car'

const inStream = fs.createReadStream('example.car');
// read and parse the entire stream in one go, this will cache the contents of
// the car in memory so is not suitable for large files.
const reader = await CarReader.fromIterable(inStream);
```
[Source](https://www.npmjs.com/package/@ipld/car)

**Question:** If I have a file at `C:\output.car`, and it's say 10GB and larger than my available RAM, how can I create a reader for this large `.car` file?

I think it should be one of these methods, but there's no sample code on how to use it...
```js
import { CarBlockIterator } from '@ipld/car/iterator';
// or
import { CarCIDIterator } from '@ipld/car/iterator';
```
[Source](https://www.npmjs.com/package/@ipld/car#CarBlockIterator)

My purpose is to upload many images from an NFT collection... I feel like adding an example of how to read a large .car file in the documentation would be helpful...

**Comment by rvagg** [comment]
You could look at both [dump-car.js](https://github.com/ipld/js-car/blob/2195e30347cda14a004f4cfd3bddb7bdcc7a0f03/examples/dump-car.js) and [verify-car.js](https://github.com/ipld/js-car/blob/2195e30347cda14a004f4cfd3bddb7bdcc7a0f03/examples/verify-car.js) in the examples directory to see this in action, just like you're wanting.

However, you're dealing directly with files so it might not be quite what you want since these are IPLD blocks, not files, and the mapping is not straightforward. What you're probably wanting to do is wrap the CAR API in [js-unixfs](https://github.com/ipld/js-unixfs), which is what web3.storage and nft.storage APIs are doing to present you with a "files" interface over the IPLD blocks. When you see their API docs @ https://web3.storage/docs/reference/js-client-library/, both the `files()` and `unixFsIterator()` iterators do this translation for you, taking the IPLD blocks, passing them through js-unixfs to see the underlying file objects.

I hope this helps!
